import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {Router} from "@angular/router";
import {DataService} from "../../../services/data.service";
import {FormsModule} from "@angular/forms";
import {SearchPipe} from "./search.pipe";

@Component({
  selector: 'app-ticketing',
  standalone: true,
  imports: [CommonModule, FormsModule, SearchPipe],
  templateUrl: './ticketing.component.html',
  styleUrl: './ticketing.component.scss'
})
export class TicketingComponent {

  constructor(private router: Router, private dataService: DataService) {}

  tableData = [
    { id: 1,
      customerName: 'Mark',
      customerEmail: 'mark@gmail.com',
      title: 'New Ticket 3',
      description: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      status: 'open',
      messages:[
        { id: 1,
          customerName: 'Mark',
          customerEmail: 'mark@gmail.com',
          user: 'admin',
        },
        { id: 2,
          customerName: 'Mark',
          customerEmail: 'mark@gmail.com',
          user: 'user',
        },
        { id: 3,
          customerName: 'Mark',
          customerEmail: '',
          user: 'admin',
        },
        { id: 4,
          customerName: 'Mark',
          customerEmail: 'mark@gmail.com',
          user: 'admin',
        },
        { id: 5,
          customerName: 'Mark',
          customerEmail: 'mark@gmail.com',
          user: 'user',
        },
        { id: 6,
          customerName: 'Mark',
          customerEmail: '',
          user: 'admin',
        }
      ]
    },
    { id: 2,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 3,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 4,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 5,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 6,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 7,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 8,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 9,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 10,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 11,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 12,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 13,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    },
    { id: 14,
      customerName: 'Paul',
      customerEmail: 'paul@gmail.com',
      title: 'New ticket 2',
      description: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      status: 'closed',
    },
    { id: 15,
      customerName: 'Claire',
      customerEmail: 'claire@gmail.com',
      title: 'New ticket 3',
      description: 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
      status: 'processing',
    }
  ];

  searchText: string = '';

  openDetailPage(data: any) {
    this.dataService.setCurrentRowData(data);
    this.router.navigate(['/home/ticketing/' + data.id]);
  }

}
